### ISSUE TITLE
Add git tags for rc releases

### ISSUE THREAD

**Issue by bjeanes** [timberio/timber-ruby#106]
Hi, it looks like only rc1 and rc5 have been tagged in Git. Any chance the others can be tagged? I'm in the habit of checking the diffs of gems when I upgrade them and it makes it much easier to identify the commit ranges. Since other releases have been tagged, I'm assuming this is an omission rather than intent. If not, then no worries—just a minor request :)

**Comment by binarylogic** [comment]
Yep, that was an oversight on my part, I'll get them tagged.

**Comment by binarylogic** [comment]
Should be good, let us know if you notice anything else.
