### ISSUE TITLE
Installer throws OpenSSL error when using SSLV3

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-ruby#161]
Outdated versions of OpenSSL will throw this error when installing Timber:

```
SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert internal error on timber install
```

SSL v3 is not supported because the SSL v3 protocol is susceptible to the POODLE vulnerability. This is a protocol issue and not a library issue. The majority of systems have disabled SSL v3 support since late 2014 when the vulnerability was publicly announced. This includes all major browsers.

As such, the Ruby OpenSSL library should fallback to a different protocol, but it does not. This can be reproduced by setting the SSL version directly on the HTTP client:

```ruby
http = Net::HTTP.new(TIMBER_API_URI.host, TIMBER_API_URI.port)
http.use_ssl = true
http.ssl_version = :SSLv3
```

Which raises:

```
#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert protocol version>
```

Setting the protocol to `: SSLv23` resolves the issue.

**Comment by DavidAntaramian** [comment]
@binarylogic Our service will not support SSLv2_3. It must be TLSv1, TLSv1_1, or TLSv1_2.
