### ISSUE TITLE
undefined method `with' for Timber::CurrentContext:Class

### ISSUE THREAD

**Issue by mrsweaters** [timberio/timber-ruby#204]
Trying to upgrade to the 3.0.0 version of the gem from a legacy integration.

```
Failure/Error: Timber.with_context(user_context, &block)
     
     NoMethodError:
       undefined method `with' for Timber::CurrentContext:Class
```

I'm calling this method in ApplicationController:

```rb
  def set_user_context(&block)
    if !current_user.nil?
      user_context = Timber::Contexts::User.new(id: current_user.id)
      Timber.with_context(user_context, &block)
    else
      block.call
    end
  end
```

Is this still applicable or has the syntax changed?

**Comment by binarylogic** [comment]
Hi @mrsweaters that shouldn't be the case. We'll take a look and see what's going on.

**Comment by binarylogic** [comment]
@mrsweaters you should be good to go with v3.0.1, let me know if that helps.
