### ISSUE TITLE
Output Backtrace in Development or via Configuration

### ISSUE THREAD

**Issue by r3dpointsp** [timberio/timber-ruby#206]
The backtrace is lost in development since timber only outputs the message. If in development/message only formatter and there is a backtrace, output it as well in a manner compatible with default Rails.

**Comment by binarylogic** [comment]
Hey @r3dpointsp, we actually recommend not using the Timber output in development. This way you can customize your development environment as you see fit. You can do this by only installing timber in your `environments/production.rb` file, or wrapping the Timber installation in a `if Rails.env.production?` block.

I hope that helps.

**Comment by r3dpointsp** [comment]
Thanks. Definitely points me in the right direction. Noting I have to then only use a single argument Logger method that takes just a hash instead of the two argument logger method on Timber's logger. The following works when Timber is installed and uninstalled:
```
Rails.logger.info({message: "test"})
```
