### ISSUE TITLE
Error in staging and no more logs are shown

### ISSUE THREAD

**Issue by augustosamame** [timberio/timber-ruby#74]
Hi I am getting this error in the Timber console and no more logs are shown:

`Could not log "start_processing.action_controller" event. NameError: uninitialized constant Timber::Events::ControllerCall::SANITIZED_VALUE`

followed by a long traceback

This does not happen in production, only in staging.
To differentiate between the 2, I am using an environment variable:

production.rb

```
  # Install the Timber.io logger, send logs over HTTP
  log_device = Timber::LogDevices::HTTP.new(ENV["TIMBER_API_KEY"])
  logger = Timber::Logger.new(log_device)
  logger.level = config.log_level
  config.logger = ActiveSupport::TaggedLogging.new(logger)

```
Rails 5.0.2 EC2 Ubuntu 16.04

**Comment by binarylogic** [comment]
Hi @augustosamame, thanks for your reporting this. We've released a fix for this via `2.0.9`. If you `bundle update timber` you should be good to go. Let us know if you need anything else.
