### ISSUE TITLE
Timber causes 500 if Rack env contains Symbol keys

### ISSUE THREAD

**Issue by bjeanes** [timberio/timber-ruby#85]
Example exception: https://sentry.io/share/issue/3136313033372e323738373237393632/

It's not uncommon for certain middleware to add their own keys to the rack env that have nothing to do with HTTP. Often, these are symbols. In my case, the authentication library Clearance is doing this.

**Comment by binarylogic** [comment]
Ah, thanks for reporting. We'll get a test in place and release an update today.

**Comment by binarylogic** [comment]
Ok, we released v `2.0.22`. Can you confirm the issue is resolved? Thanks for reporting it!

**Comment by bjeanes** [comment]
Yep that seems to do the trick.
